services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty
    restart: unless-stopped
    ports:
      - "8000:8000" # HTTP (redirects to HTTPS)
      - "8443:8443" # Main UI
      - "25565:25565" # Minecraft Java default port
    environment:
      - TZ=Asia/Kathmandu
    volumes:
      - ./crafty/backups:/crafty/backups
      - ./crafty/logs:/crafty/logs
      - ./crafty/servers:/crafty/servers
      - ./crafty/config:/crafty/config
      - ./crafty/import:/crafty/import
