networks:
  db:
    external: true

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis_password"]
    volumes:
      - redis-data:/data
    networks:
      - db

volumes:
  redis-data:
